### ISSUE TITLE
Fails to compile for WatchOS

### ISSUE THREAD

**Issue by mtichenor-vivint** [segment-integrations/analytics-swift-mixpanel#4]
The `initialize` method for Mixpanel version 4.0.3 does not support the trackAutomaticEvents parameter on WatchOS or OSX. Consequently, this library fails to compile if the project has a WatchOS build target. 

The fix for this issue is to change MixpanelDestination.swift line 73 to the following:
```
#if !os(OSX) && !os(watchOS)
            mixpanel = Mixpanel.initialize(token: token, trackAutomaticEvents: false)
#else
            mixpanel = Mixpanel.initialize(token: token)
#endif
```

**Comment by bsneed** [comment]
Sorry for the delay on this @mtichenor-vivint.  We recently added auto-JIRA ticket creation internally to fix these unanswered issues on some destinations.
